### ISSUE TITLE
Found problem with certain calendars

### ISSUE THREAD

**Issue by ralbright-wa** [firstone/holidays-google-poly#1]
I am using your plugin to track whether my elementary age daughter has a normal school day, late start or half day. These 3 schedules correspond to three individual calendars in my google calendar (aptly named, School Schedule, School - Half Day and School - Late Start). Only one of any of the three of those is on my calendar on any given day. I have a program that checks the next days events and announces at 7pm if the day is late start or half day. However for some reason, on Monday it announced that the following day was a late start (even though the calendar points to that not being the case.) This morning (Tuesday) I looked at my ISY, and it shows that both today and tomorrow are late start (IE they are True).

So something is not working correctly on the polling when you poll multiple calendars. Any ideas?

![Calendar](https://user-images.githubusercontent.com/54728334/65051033-36e88d80-d91d-11e9-9542-6b0fd461e00e.png)
![ISY](https://user-images.githubusercontent.com/54728334/65051034-36e88d80-d91d-11e9-8622-72b83ae149f4.png)

**Comment by firstone** [comment]
Right click on calendar controller node and click 'Query' and see what the states are. Sometimes ISY goes out of sync with node server or polyglot. If it's still incorrect, make sure calendars are created with correct time zone and also send log file to me, please.

**Comment by ralbright-wa** [comment]
> Right click on calendar controller node and click 'Query' and see what the states are. Sometimes ISY goes out of sync with node server or polyglot. If it's still incorrect, make sure calendars are created with correct time zone and also send log file to me, please.

Well that updated ISY correctly to show the correct data now.... that was weird.

**Comment by ralbright-wa** [comment]
Should I have the Holidays Google Calendar set to query on a daily basis to keep this from getting out of sync?

**Comment by firstone** [comment]
It's fairly known issue. Some people add Query into the program once a day or more.

**Comment by ralbright-wa** [comment]
> It's fairly known issue. Some people add Query into the program once a day or more.

Must have missed that.... added a program so that it queries once a day now. Thank you for your QUICK responses. The wife will be a lot happier with me now. (Not getting the wrong notifications.)
