### ISSUE TITLE
What is the custom parameter name for the token?

### ISSUE THREAD

**Issue by psmith3** [firstone/holidays-google-poly#2]
Is the parameter name "token"? I have tried several times to get this to work without luck.

**Comment by firstone** [comment]
When you start it up without doing any configuration, it should pop up a notice with authentication URL. When you click on it, it opens a browser and asks you to login. Once you login, you get a token. Save that token into parameter name "token". It's not a regular parameter that you can just name. If you don't see those, it's possible your polyglot might need updating. Which version are you running?

**Comment by psmith3** [comment]
Thanks. I am running Polyglot Version 2.2.3
