### ISSUE TITLE
Wrong SSL version number in logs

### ISSUE THREAD

**Issue by macjeff** [firstone/holidays-google-poly#3]
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2555)

Should I ignore that?  Seems to be working fine in Polisy

**Comment by macjeff** [comment]
Can you explain what this means?

**Comment by firstone** [comment]
SSL is not used directly so I don't know for sure where it's coming from. Try fetching following libs by hand and see if it goes away.

google-api-python-client
google-auth-httplib2
google-auth-oauthlib

I'll try it when I get a chance.
If it works though, why touch it.

**Comment by macjeff** [comment]
ok its working so go ahead and close this if you want
